# Generated by Django 5.1.1 on 2024-09-24 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_block"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="blocked",
        ),
        migrations.RemoveField(
            model_name="block",
            name="blocker",
        ),
        migrations.AddField(
            model_name="block",
            name="blocked_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
