# Generated by Django 5.1.1 on 2024-09-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatroom_members"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockedUser",
        ),
    ]
