# Generated by Django 5.1.1 on 2024-09-24 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_delete_blockeduser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
