# Generated by Django 5.1.1 on 2024-09-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_chatroom_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="members",
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("date_added",)},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="date_added",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="message_content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.AddField(
            model_name="message",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(default="default_username", max_length=50),
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.room",
            ),
        ),
        migrations.DeleteModel(
            name="Block",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
