# Generated by Django 5.1.1 on 2024-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_room_remove_chatroom_members_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="username",
            field=models.CharField(max_length=50),
        ),
    ]
