# Generated by Django 5.1.1 on 2024-09-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_message_room_alter_message_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_content",
            field=models.TextField(max_length=500),
        ),
    ]
